### ISSUE TITLE
File readings fails

### ISSUE THREAD

**Issue by Zardoz89** [SanguineHaze/CharacterCreator#1]
I try your "Linux" version, I'm getting troubles with the paths to the datafiles. 

`
/home/luis/NPC\sourceData\Race.txt (No existe el archivo o el directorio)
/home/luis/NPC\sourceData\Subrace.txt (No existe el archivo o el directorio)
/home/luis/NPC\sourceData\NameDefault.txt (No existe el archivo o el directorio)
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at Name.generateBeginning(Name.java:155)
        at Name.<init>(Name.java:36)
        at CharacterCreator.main(CharacterCreator.java:12)
`

Java should allow to make a program to run across different OS without issues, so I don't know that do you exactly with the File paths to get this kins of troubles, but 

1) Use File.separator and/or new File(File parent, String child) to build paths. Try to avoid use Strings to store paths! . For example, on line 93 of Name.java , could be : 
`
File nameListTargetFile = new File (filesDirectory, "sourceData" + File.separator + "NameDefault.txt" );`

2) You should try to use OS standards paths to search for resources, or at least relative paths where the executable is . Check this : http://stackoverflow.com/a/17939617

**Comment by SanguineHaze** [comment]
Hi,

Thanks for your email! That's a pretty neat trick - didn't know what one
before. I've updated the ZIP to use your suggestion, but I don't have a
Linux OS anywhere near me right now. Could you test this to make sure it's
been correctly updated?

https://dl.dropboxusercontent.com/u/12555331/NPC%20Generator%20-%20Linux%20Attempt.zip

Thanks!

-Dylan
